# In order for the prompt to work correctly you'll need to git clone
# https://github.com/sindresorhus/pure then pull async.zsh and pure.zsh.
# Both files (or symlinks) need to end up in $HOME/.zfunctions

# Start out by pulling all of the basic unix shell configuration.
#emulate sh -c '. ~/.profile'
#
export PATH=/Users/alexl/.local/bin:$PATH
VIRTUALENVWRAPPER_PYTHON=$(which python3)

export PATH=/usr/local/anaconda3/bin:"$PATH" 2> /dev/null
export PATH="/usr/local/opt/make/libexec/gnubin:$PATH"

# ------------------------ Shell History Configuration ------------------------
setopt extended_history       # record timestamp of command in HISTFILE
setopt hist_expire_dups_first # delete duplicates first when HISTFILE size exceeds HISTSIZE
setopt hist_ignore_dups       # ignore duplicated commands history list
setopt hist_ignore_space      # ignore commands that start with space
setopt hist_verify            # show command with history expansion to user before running it
setopt inc_append_history     # add commands to HISTFILE in order of execution
setopt share_history          # share command history data

setopt HIST_IGNORE_DUPS     # Remove immediate duplicates
setopt HIST_IGNORE_ALL_DUPS # No really, ignore duplicates
setopt HIST_SAVE_NO_DUPS
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_FIND_NO_DUPS

setopt HIST_REDUCE_BLANKS   # Why is this not a default?
setopt HIST_IGNORE_SPACE    # Don't save left justified spaces
setopt HIST_NO_STORE        # No really, fuck spaces
setopt EXTENDED_HISTORY     # Save start time and wall time of command

# ------------------------------ Completion Stuff ------------------------------

bindkey -M viins '\C-i' complete-word

# Faster! (?)
zstyle ':completion::complete:*' use-cache 1

# case insensitive completion
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

zstyle ':completion:*' verbose yes
zstyle ':completion:*:descriptions' format '%B%d%b'
zstyle ':completion:*:messages' format '%d'
zstyle ':completion:*:warnings' format 'No matches for: %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' completer _expand _complete _approximate _ignored


# generate descriptions with magic.
zstyle ':completion:*' auto-description 'specify: %d'

# Don't prompt for a huge list, page it!
zstyle ':completion:*:default' list-prompt '%S%M matches%s'

# Don't prompt for a huge list, menu it!
zstyle ':completion:*:default' menu 'select=0'

# Have the newer files last so I see them first
zstyle ':completion:*' file-sort modification reverse

# color code completion!!!!  Wohoo!
zstyle ':completion:*' list-colors "=(#b) #([0-9]#)*=36=31"

unsetopt LIST_AMBIGUOUS

function load_ssh_keys {
    #declare -a potential_keys=("/Users/alexl/.ssh/github" "/Users/alexl/.ssh/versive_github"  "/Users/alexl/.ssh/esentire_github" "/Users/alexl/.ssh/general_key" "/Users/alexl/.ssh/github")

    eval $(ssh-agent -s)
    ssh-add "/Users/alexl/.ssh/github" "/Users/alexl/.ssh/versive_github"  "/Users/alexl/.ssh/esentire_github" "/Users/alexl/.ssh/general_key" "/Users/alexl/.ssh/github"
}

# ---------------------------------- Prompt ----------------------------------
# This was the source used to create this
# https://wiki.archlinux.org/index.php/zsh#Prompts
#
autoload colors && colors
PS1='%F{cyan}%n@%m %~%f %(?.%F{green}:).%F{red}[%?] :( )%#%f '
export PATH="/usr/local/opt/libpq/bin:$PATH"

load_ssh_keys
